Documentation/(sakuli/sakuli dashboard#61)/dashboard info
sakuli/sakuli.github.io pull request #132
Opened 2020-08-24 10:17 UTC by cliffle

2020-08-26 10:01 UTC, ZNicoZ commented on data/en/features_enterprise.yml
> +                  - liEl: Configurable play button to perform actions on Kubernetes/Openshift clusters
```suggestion
                  - liEl: Configurable play button to start sakuli tests on Kubernetes/Openshift clusters
```

2020-08-26 10:02 UTC, ZNicoZ commented on data/en/features_enterprise.yml
> +                  - liEl: Trigger your Sakuli test on your cluster with the play button and watch it perform in real-time
```suggestion
                  - liEl: Watch your Sakuli test in real-time with the integrated VNC display
```

2020-08-26 10:03 UTC, ZNicoZ commented on data/en/features_enterprise.yml
> +                  - liEl: Start your Sakuli test automatically with a cronjob to monitor your application continuously
```suggestion
                  - liEl: Automated start of your Sakuli tests in defined cycles to monitor your application continuously
```

2020-08-26 10:04 UTC, ZNicoZ commented on data/en/features_enterprise.yml
> +                  - liEl: Embed your monitoring metrics on the dashboard to check the performance of your application
```suggestion
                  - liEl: Embed your monitoring frontend to the dashboard and monitor the performance of your application
```

2020-08-31 05:58 UTC, svettwer requested changes
Sorry for another iteration but as nico is on vacation, I took his review task.

2020-08-31 05:58 UTC, svettwer commented on data/de/features_enterprise.yml
> +                  - liEl: Automatisierter Start Ihrer Sakuli Tests in bestimmten Zeitintervallen, um Ihre Anwendung fortlaufend zu überwachen
```suggestion
                  - liEl: Konfigurierbarer Start Button um einen Sakuli Test auf einem Kubernetes/Openshift Cluster auszuführen.
                  - liEl: Beobachten Sie die Testausführung live über das im Dashboard eingebundene VNC Display.
                  - liEl: Automatisierter Start Ihrer Sakuli Tests in bestimmten Zeitintervallen, um Ihre Anwendung fortlaufend zu überwachen.
```

2020-08-31 05:58 UTC, svettwer commented on data/de/features_enterprise.yml
> +                  - liEl: Einbindung Ihres Monitoring Frontends um die Leistung Ihrer Anwendung kontinuierlich zu überwachen.
```suggestion
                  - liEl: Einbindung Ihres Monitoring Frontends um die Leistung Ihrer Anwendung kontinuierlich im Blick zu behalten.
```

2020-08-31 05:58 UTC, svettwer commented on data/en/features_enterprise.yml
> +            - paragraph : Start and supervision of your Sakuli test und display of monitoring data in real-time.
```suggestion
            - paragraph : Start and supervision of your Sakuli test and display of monitoring data in real-time.
```

2020-08-31 05:58 UTC, svettwer commented on data/en/features_enterprise.yml
> +                  - liEl: Embed your monitoring frontend to the dashboard and monitor the performance of your application
```suggestion
                  - liEl: Configurable play button to start Sakuli tests on Kubernetes/Openshift clusters.
                  - liEl: Watch your Sakuli test in real-time with the integrated VNC display.
                  - liEl: Automated scheduling of your Sakuli test to monitor your application continuously.
                  - liEl: Embed your monitoring frontend to the dashboard and monitor the performance of your application.
```

2020-08-31 07:07 UTC, svettwer approved these changes

2020-08-31 07:25 UTC, merged